### ISSUE TITLE
interesting package

### ISSUE THREAD

**Issue by shaunc** [micro-toolkit/logger-facade-nodejs#6]
I am currently using bunyan in several applications. However, I'm getting ready to spin off part of them as a library, and wanted to release it as "agnostic" to users' logger preferences. Googling came up with your package -- it looks like its aiming toward what I want, but thought I'd ask...

1) Is my purpose a good/intended use for the package? Or am I missing something?
2) Whether you intend to support it? Doesn't seem like much activity, and bunyan is a pretty common logger...? Writing a wrapper looks pretty simple... but...
3) Bunyan (and I'm sure other loggers) support "child loggers". It would seem that getLogger() returns an instance that multiplexes log calls to all registered instances... but you tack on the name to the start. So do you intend that the bunyan wrapper (or whatever) would create a child based on the name? 

4) Shouldn't there be a "log level" interface to the loggers? Or if you intend that they be registered "pre-configured"? If so, shouldn't the name be used to select a logger rather than multiplexing the signals?

**Comment by pjanuario** [comment]
@shaunc Since I started to build node applications I have been sturggling to find/discover the appropriate set of tools and logging was one of them. So my initial goal was to provide logger facade, working as contract and that would allow plugin different outputs.

Why? 
1. because i prefer to have contract dependencies than implementation dependencies and with this design i can plug in almost every logger implementation that i wanted;
2. I use different logging on different environments, console in development and airbrake/errbit and file in json to centralize on logstash. So using this kind of interface I could easily deal with this, avoid having different code for different environments. 

For now I just have a few appenders but the idea is to grow as someone needs and/or implement it.

Responding to your questions:
1) I think this feets with your need and will alow you to control plugin different libraries easily.
2) Support bunyan? I recently find out about bunyan and wiston, I will probably plugin wiston in the next couple of weeks and be using it in production also. So, I wouldn't implement bunyan integration for now, but feel free to open a pull request and contact me if you need some help.
3) I have to read a little bit about child loggers at least with this "name" I not aware what is trying to solve.  Can you please explain what problem does child logger solves.
4) Can you please explain what you mean about "log level" interfaces? I also didn't get with second part of the question. Logger facade works as facade and specific log implementations can be plugged in: such as console, airbrake, wiston, bunyan ...

I hope my response have been clarifying, feel free to ask more info or for some help.

I think if you are planning to use this, I also would like to tell you that this package is currently used in production in several applications. One of those is a ZeroMQ Service Suite library to build microservices architectures with frictionless, that is open source http://pjanuario.github.io/zmq-service-suite-specs/

Regarding to future, I pretend to add wiston appender in the next weeks.

Thank your for your feedback and interest.

**Comment by shaunc** [comment]
@pjanuario -- thanks for your response. 
- _child loggers_ -- the idea is to customize log output for a particular component of the application. (See [bunyan doc](https://github.com/trentm/node-bunyan#logchild) for an example. For instance, one of the things I'm spinning out is a transaction manager. Including the relevant transaction name is important. Hmm... it might be possible to use the "name" of the logger instance to select a child logger behind the facade... 
- _logLevel_ -- some interface (per logger interface) to completely suppress passing on messages below a  given level. It would be easy enough to add (I could send a pull request if you like) -- but perhaps you think that sort of thing is the responsibility of the downstream log provider. (That was the thought the second part of the question was trying to ask.)

**Comment by shaunc** [comment]
Hmm.. one problem I see is that its hard to write logger calls completely agnostically. For instance, bunyan writes json and I want to pass metadata, but your console logger facade will have trouble
with json.

May I suggest that all loggers support format such as:

```
info([metadata], message, [optional arguments])
```

I think this would be a non-breaking change: metadata would be an object. So if the first argument is a string, we can conclude that metadata is absent, and current calls in form:

```
info(message, [arguments])
```

Would be processed without change? Again ... I could give you a pull request, but only if you are interested ;). current loggers could ignore metadata if present or (better) put in form "key=value, ..." after formatted message.

**Comment by pjanuario** [comment]
@shaunc sorry about the late response, but it was a long weekend! :)

Regarding with child loggers I had read a little bit about it also and it seems a nice feature to introduce on the library. I already open a issue for that #7.

Regarding the log level, the idea is to pass this responsibility to the appender, it's seems more flexible to me. Do you see any scenario where you would benefit from having it on the logger facade?

Regarding with metadata, that was already on my mind since I also want that info to pass to logstash and your solution seems nice.

So I will be patiently waiting for your pull requests! :smile: 
And probably stick with bunyan instead of winston for now.

Thanks for your support.

**Comment by pjanuario** [comment]
@shaunc ping me if you have any more doubts.
